baseURL = "https://wlyn.ch/"
languageCode = "en-us"
title = "Billy Lynch"
theme = "hyde"
googleAnalytics = "UA-51544701-1"
publishDir = "docs"

pygmentsCodeFences = true

[params]
  themeColor = "theme-base-0d"
  description = " "
	avatarurl = "static/profile.jpg"

[Menus]
  main = [
      {Name = "GitHub", URL = "https://github.com/wlynch"},
  ]
